import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0d1929" },
  content: { padding: 20 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    marginBottom: 16,
    textTransform: "uppercase",
  },
  profileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 20,
  },
  profileChip: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.2)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  profileChipActive: {
    backgroundColor: "rgba(0,48,120,0.5)",
    borderColor: "#00a3e0",
  },
  profileChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.7)",
  },
  profileChipTextActive: { color: "white" },
  profileCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.3)",
  },
  profileLabel: {
    fontSize: 10,
    color: "#00a3e0",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 4,
  },
  profileName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "white",
    marginBottom: 8,
  },
  profileDesc: { fontSize: 12, color: "rgba(255,255,255,0.6)", lineHeight: 18 },
  card: {
    backgroundColor: "#0d1929",
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.2)",
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 10,
    color: "#00a3e0",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 12,
  },
  priorities: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  priorityTag: {
    backgroundColor: "rgba(0,163,224,0.15)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  priorityText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#00a3e0",
    textTransform: "uppercase",
  },
  highlight: {
    backgroundColor: "rgba(0,163,224,0.08)",
    borderRadius: 8,
    padding: 14,
  },
  highlightText: {
    fontSize: 13,
    color: "rgba(255,255,255,0.85)",
    lineHeight: 20,
    fontStyle: "italic",
  },
  listItem: { marginBottom: 6 },
  listText: { fontSize: 13, color: "rgba(255,255,255,0.8)", lineHeight: 20 },
  closingQuote: {
    borderRadius: 14,
    padding: 18,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.25)",
  },
  closingLabel: {
    fontSize: 9,
    color: "#f5a623",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 8,
  },
  closingText: {
    fontSize: 14,
    color: "white",
    fontWeight: "600",
    lineHeight: 20,
    fontStyle: "italic",
  },
  emptyState: { alignItems: "center", paddingVertical: 60 },
  emptyIcon: { fontSize: 48, marginBottom: 16 },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "rgba(255,255,255,0.5)",
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 12,
    color: "rgba(255,255,255,0.3)",
    textAlign: "center",
  },
});