import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0d1929" },
  content: { padding: 20 },
  heroCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.3)",
  },
  heroLabel: {
    fontSize: 10,
    color: "#f5a623",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 4,
  },
  heroTitle: { fontSize: 20, fontWeight: "bold", color: "white" },
  card: {
    backgroundColor: "#0d1929",
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.2)",
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 10,
    color: "#00a3e0",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 12,
  },
  cardText: { fontSize: 13, color: "rgba(255,255,255,0.8)", lineHeight: 20 },
  listItem: { marginBottom: 8 },
  listText: { fontSize: 13, color: "rgba(255,255,255,0.8)", lineHeight: 20 },
  highlightCard: {
    backgroundColor: "rgba(0,163,224,0.08)",
    borderLeftWidth: 3,
    borderLeftColor: "#00a3e0",
    borderRadius: 12,
    padding: 16,
    marginVertical: 12,
  },
  highlightText: {
    fontSize: 13,
    color: "rgba(255,255,255,0.85)",
    lineHeight: 20,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  highlightSub: {
    fontSize: 13,
    color: "rgba(255,255,255,0.7)",
    lineHeight: 20,
    fontStyle: "italic",
    marginTop: 8,
  },
  closingQuote: {
    borderRadius: 14,
    padding: 18,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.25)",
  },
  closingLabel: {
    fontSize: 9,
    color: "#f5a623",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 8,
  },
  closingText: {
    fontSize: 14,
    color: "white",
    fontWeight: "600",
    lineHeight: 20,
    fontStyle: "italic",
  },
});