import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  disabledInput: {
    opacity: 0.7,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  notFoundCard: {
    backgroundColor: "rgba(239,68,68,0.08)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.35)",
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  notFoundTitle: {
    color: "#ef4444",
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 8,
  },
  notFoundText: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 8,
  },
  notFoundHint: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    fontStyle: "italic",
  },
  container: { flex: 1, backgroundColor: "#0d1929" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: "rgba(0,48,120,0.95)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,163,224,0.2)",
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  backButtonText: { color: "white", fontSize: 22, fontWeight: "bold" },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 1,
  },
  badge: {
    backgroundColor: "#00a3e0",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "white",
    textTransform: "uppercase",
  },
  content: { padding: 20 },
  infoCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.3)",
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "white",
    marginBottom: 8,
  },
  infoText: { fontSize: 12, color: "rgba(255,255,255,0.7)", lineHeight: 18 },
  form: { marginBottom: 24 },
  inputGroup: { marginBottom: 16 },
  label: {
    fontSize: 10,
    color: "#00a3e0",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 8,
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.2)",
    borderRadius: 12,
    padding: 14,
    color: "white",
    fontSize: 14,
  },
  searchBtn: {
    backgroundColor: "#00a3e0",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 8,
    shadowColor: "#00a3e0",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  searchBtnDisabled: { opacity: 0.5 },
  searchBtnText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  validationSection: {
    backgroundColor: "rgba(245,166,35,0.08)",
    borderWidth: 1,
    borderColor: "rgba(245,166,35,0.3)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  validationTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#f5a623",
    marginBottom: 8,
  },
  validationText: {
    fontSize: 11,
    color: "rgba(255,255,255,0.6)",
    marginBottom: 12,
    lineHeight: 16,
  },
  validationBtn: {
    backgroundColor: "#f5a623",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  validationBtnText: { color: "#0d1929", fontSize: 13, fontWeight: "bold" },
  similarSection: {
    backgroundColor: "rgba(0,163,224,0.08)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.2)",
  },
  similarTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#00a3e0",
    marginBottom: 12,
  },
  similarItem: { paddingVertical: 8 },
  similarText: { fontSize: 13, color: "rgba(255,255,255,0.8)" },
  availableSection: {
    backgroundColor: "#0d1929",
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.2)",
    borderRadius: 16,
    padding: 16,
  },
  availableTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "white",
    marginBottom: 12,
  },
  availableList: {
    fontSize: 12,
    color: "rgba(255,255,255,0.6)",
    lineHeight: 20,
    marginBottom: 12,
  },
  note: { fontSize: 10, color: "rgba(255,255,255,0.3)", fontStyle: "italic" },
});