import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0d1929" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: "rgba(0,48,120,0.95)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,163,224,0.2)",
  },

  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },

  backText: {
    fontSize: 24,
    color: "white",
    fontWeight: "bold",
  },

  headerTitle: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 62,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 1,
  },

  headerSpacer: {
    width: 36,
    height: 36,
  },
  content: { padding: 20 },
  summaryCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.3)",
  },
  summaryContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryLabel: {
    fontSize: 10,
    color: "#00a3e0",
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  summaryVs: {
    fontSize: 11,
    color: "rgba(255,255,255,0.4)",
    marginVertical: 4,
  },
  summaryRival: {
    fontSize: 12,
    color: "rgba(255,255,255,0.6)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  advantageBox: { alignItems: "center" },
  advantageCount: {
    fontFamily: "System",
    fontSize: 36,
    fontWeight: "bold",
    color: "#00c853",
  },
  advantageLabel: {
    fontSize: 9,
    color: "rgba(255,255,255,0.4)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  card: {
    backgroundColor: "#0d1929",
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.2)",
    borderRadius: 16,
    overflow: "hidden",
  },
  resultRow: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  resultAttr: {
    fontSize: 10,
    color: "#00a3e0",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  resultValues: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  resultValLeft: {
    fontSize: 11,
    color: "rgba(255,255,255,0.8)",
    flex: 1,
    textAlign: "left",
  },
  resultValRight: {
    fontSize: 11,
    color: "rgba(255,255,255,0.8)",
    flex: 1,
    textAlign: "right",
  },
  resultBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginHorizontal: 8,
  },
  resultBadgeText: { fontSize: 9, fontWeight: "bold", letterSpacing: 0.5 },
  badgeGreen: { backgroundColor: "rgba(0,200,83,0.15)" },
  badgeRed: { backgroundColor: "rgba(255,61,0,0.15)" },
  badgeYellow: { backgroundColor: "rgba(255,214,0,0.15)" },
  badgeGray: { backgroundColor: "rgba(84,110,122,0.15)" },
  actionButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  actionBtn: {
    flex: 1,
    minWidth: "48%",
    backgroundColor: "#003078",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  actionBtnSecondary: { backgroundColor: "rgba(255,255,255,0.06)" },
  actionBtnText: { color: "white", fontSize: 13, fontWeight: "bold" },
  emptyContainer: {
    flex: 1,
    backgroundColor: "#0d1929",
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  emptyIcon: { fontSize: 48, marginBottom: 16 },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "rgba(255,255,255,0.5)",
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 12,
    color: "rgba(255,255,255,0.3)",
    marginBottom: 20,
    textAlign: "center",
  },
  emptyButton: {
    backgroundColor: "#00a3e0",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 14,
  },
  emptyButtonText: { color: "white", fontWeight: "bold" },
});