import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0d1929" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: "rgba(0,48,120,0.95)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,163,224,0.2)",
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonText: { color: "white", fontSize: 22, fontWeight: "bold" },
  shareButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(0,163,224,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  shareButtonText: { fontSize: 18 },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 1,
  },
  content: { padding: 20 },
  vehicleCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.3)",
  },
  vehicleLabel: {
    fontSize: 10,
    color: "#00a3e0",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 8,
  },
  vehicleName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    marginBottom: 4,
  },
  vehicleModel: { fontSize: 12, color: "rgba(255,255,255,0.6)" },
  searchQuery: {
    backgroundColor: "rgba(0,163,224,0.1)",
    borderRadius: 8,
    padding: 8,
    marginTop: 12,
  },
  searchQueryText: { fontSize: 10, color: "#00a3e0", textAlign: "center" },
  statsCard: {
    backgroundColor: "rgba(0,163,224,0.08)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  statsText: {
    fontSize: 12,
    color: "#00a3e0",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  progressBar: {
    height: 4,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 2,
    overflow: "hidden",
  },
  progressFill: { height: "100%", backgroundColor: "#00c853", borderRadius: 2 },
  specsCard: {
    backgroundColor: "#0d1929",
    borderWidth: 1,
    borderColor: "rgba(0,163,224,0.2)",
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
  },
  specsTitle: {
    backgroundColor: "rgba(0,163,224,0.1)",
    padding: 14,
    fontSize: 11,
    fontWeight: "bold",
    color: "#00a3e0",
    textTransform: "uppercase",
    letterSpacing: 1,
    textAlign: "center",
  },
  specsSubtitle: {
    fontSize: 9,
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    paddingHorizontal: 14,
    paddingBottom: 8,
  },
  specRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  specLabel: {
    fontSize: 13,
    color: "rgba(255,255,255,0.7)",
    flex: 1,
    flexWrap: "wrap",
  },
  specValueBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    minWidth: 110,
    alignItems: "center",
  },
  availableBadge: { backgroundColor: "rgba(0,200,83,0.15)" },
  unavailableBadge: { backgroundColor: "rgba(255,61,0,0.1)" },
  specValue: { fontSize: 11, fontWeight: "bold", color: "#00c853" },
  unavailableText: { color: "#ff3d00" },
  noteCard: {
    backgroundColor: "rgba(84,110,122,0.1)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
  },
  noteTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#f5a623",
    marginBottom: 6,
  },
  noteText: { fontSize: 10, color: "rgba(255,255,255,0.5)", lineHeight: 16 },
  newSearchBtn: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginBottom: 20,
  },
  newSearchBtnText: { color: "white", fontSize: 15, fontWeight: "bold" },
  emptyContainer: {
    flex: 1,
    backgroundColor: "#0d1929",
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  emptyIcon: { fontSize: 48, marginBottom: 16 },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "rgba(255,255,255,0.5)",
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 12,
    color: "rgba(255,255,255,0.3)",
    marginBottom: 20,
    textAlign: "center",
  },
  emptyButton: {
    backgroundColor: "#00a3e0",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 14,
  },
  emptyButtonText: { color: "white", fontWeight: "bold" },
});